const object = [
    {
        id:1,
        img:"./images/image 1.png",
        Country:"USA",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    { 
        id:2,
        img:"./images/image 1.png",
        Country:"Australia",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:3,
        img:"./images/image 1.png",
        Country:"UK",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:4,
        img:"./images/image 1.png",
        Country:"UK",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:5,
        img:"./images/image 1.png",
        Country:"UK",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:6,
        img:"./images/image 1.png",
        Country:"Canada",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:7,
        img:"./images/image 1.png",
        Country:"New zealand",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:8,
        img:"./images/image 1.png",
        Country:"Singapore",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:9,
        img:"./images/image 1.png",
        Country:"Ireland",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:10,
        img:"./images/image 1.png",
        Country:"Germany",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:11,
        img:"./images/image 1.png",
        Country:"UK",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:12,
        img:"./images/image 1.png",
        Country:"USA",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:13,
        img:"./images/image 1.png",
        Country:"UK",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:14,
        img:"./images/image 1.png",
        Country:"UK",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:15,
        img:"./images/image 1.png",
        Country:"Canada",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:16,
        img:"./images/image 1.png",
        Country:"Australia",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:17,
        img:"./images/image 1.png",
        Country:"New Zealand",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:18,
        img:"./images/image 1.png",
        Country:"USA",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:19,
        img:"./images/image 1.png",
        Country:"UK",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    },
    {
        id:20,
        img:"./images/image 1.png",
        Country:"Canada",
        date:"10th May 2021",
        Venue:"Zoom Meating",
        Time: "02:00 pm",
    }
]
export default object;